### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by liamxg** [avrodrigues/Tidy_tuesday#1]
loadfonts(device = "win")
Error in windowsFonts() : could not find function "windowsFonts"

**Comment by avrodrigues** [comment]
you can use other options, such as loadfonts (device = "pdf") or skip the font_import() and loadfonts() functions.
If you choose to skip functions, be aware that the 'family' argument throughout the code must also be skipped or changed

**Comment by liamxg** [comment]
thanks, i will change another font, hope this is work.

**Comment by liamxg** [comment]
kenya <- raster::getData('GADM', country='KEN', level=1) 
trying URL 'https://biogeo.ucdavis.edu/data/gadm3.6/Rsp/gadm36_KEN_1_sp.rds'
Error in utils::download.file(url = aurl, destfile = fn, quiet = FALSE,  : 
  cannot open URL 'https://biogeo.ucdavis.edu/data/gadm3.6/Rsp/gadm36_KEN_1_sp.rds'
In addition: Warning messages:
1: In raster::getData("GADM", country = "KEN", level = 1) :
  getData will be removed in a future version of raster
. Please use the geodata package instead
2: In utils::download.file(url = aurl, destfile = fn, quiet = FALSE,  :
  URL 'https://biogeo.ucdavis.edu/data/gadm3.6/Rsp/gadm36_KEN_1_sp.rds': status was 'Peer certificate cannot be authenticated with given CA certificates'
>

**Comment by liamxg** [comment]
@avrodrigues
